Visualization Manager:
  Class: ""
  Displays:
    - Class: rviz/Grid
      Name: Grid
      Enabled: true
      Plane: XY
      Cell Size: 1.0
      Color: 160;160;160

    - Class: rviz/Map
      Name: Map
      Topic: /map
      Alpha: 0.7
      Color Scheme: map
      Draw Behind: true
      Enabled: true

    - Class: rviz/LaserScan
      Name: LaserScan
      Topic: /scan
      Enabled: true
      Color: 255;0;0
      Size (m): 0.05
      Queue Size: 10

    - Class: rviz/RobotModel
      Name: RobotModel
      Enabled: true
      Robot Description: robot_description

    - Class: rviz/TF
      Name: TF
      Enabled: true
      Frame Timeout: 10.0

    - Class: rviz/PoseWithCovariance
      Name: AMCL Pose
      Topic: /amcl_pose
      Enabled: true
      Color: 0;255;0
      Alpha: 1.0

    - Class: rviz/Path
      Name: Global Path
      Topic: /move_base/GlobalPlanner/plan
      Enabled: true
      Color: 0;0;255
      Alpha: 1.0
      Line Style: Lines

    - Class: rviz/Path
      Name: Local Path
      Topic: /move_base/DWAPlannerROS/local_plan
      Enabled: true
      Color: 255;165;0
      Alpha: 1.0
      Line Style: Lines

  Fixed Frame: map
  Background Color: 0;0;0
  Frame Rate: 30
